//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/SkipMessage.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SkipMessage: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SkipMessage()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SkipMessage"",
    ""maps"": [
        {
            ""name"": ""Skip"",
            ""id"": ""f3e52d27-9d4f-4d8f-a07c-5bbe97cf23dd"",
            ""actions"": [
                {
                    ""name"": ""SkipMessage"",
                    ""type"": ""Button"",
                    ""id"": ""42ccaa62-5ff0-4f7d-b3c9-32854242b3b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4c05d605-4330-4435-a4af-deb264c1a594"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipMessage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Skip
        m_Skip = asset.FindActionMap("Skip", throwIfNotFound: true);
        m_Skip_SkipMessage = m_Skip.FindAction("SkipMessage", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Skip
    private readonly InputActionMap m_Skip;
    private List<ISkipActions> m_SkipActionsCallbackInterfaces = new List<ISkipActions>();
    private readonly InputAction m_Skip_SkipMessage;
    public struct SkipActions
    {
        private @SkipMessage m_Wrapper;
        public SkipActions(@SkipMessage wrapper) { m_Wrapper = wrapper; }
        public InputAction @SkipMessage => m_Wrapper.m_Skip_SkipMessage;
        public InputActionMap Get() { return m_Wrapper.m_Skip; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SkipActions set) { return set.Get(); }
        public void AddCallbacks(ISkipActions instance)
        {
            if (instance == null || m_Wrapper.m_SkipActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SkipActionsCallbackInterfaces.Add(instance);
            @SkipMessage.started += instance.OnSkipMessage;
            @SkipMessage.performed += instance.OnSkipMessage;
            @SkipMessage.canceled += instance.OnSkipMessage;
        }

        private void UnregisterCallbacks(ISkipActions instance)
        {
            @SkipMessage.started -= instance.OnSkipMessage;
            @SkipMessage.performed -= instance.OnSkipMessage;
            @SkipMessage.canceled -= instance.OnSkipMessage;
        }

        public void RemoveCallbacks(ISkipActions instance)
        {
            if (m_Wrapper.m_SkipActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISkipActions instance)
        {
            foreach (var item in m_Wrapper.m_SkipActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SkipActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SkipActions @Skip => new SkipActions(this);
    public interface ISkipActions
    {
        void OnSkipMessage(InputAction.CallbackContext context);
    }
}
